<a href="https://colab.research.google.com/github/shahil2104/Hibernate-ORM-Tutorials/blob/master/major_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as scs

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
df=pd.read_csv("/content/drive/My Drive/python.smartknower/training.csv",engine='python',header=None)
df

0  ...                                                  5
0        0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1        0  ...  is upset that he can't update his Facebook by ...
2        0  ...  @Kenichan I dived many times for the ball. Man...
3        0  ...    my whole body feels itchy and like its on fire 
4        0  ...  @nationwideclass no, it's not behaving at all....
...     ..  ...                                                ...
1599995  4  ...  Just woke up. Having no school is the best fee...
1599996  4  ...  TheWDB.com - Very cool to hear old Walt interv...
1599997  4  ...  Are you ready for your MoJo Makeover? Ask me f...
1599998  4  ...  Happy 38th Birthday to my boo of alll time!!! ...
1599999  4  ...  happy #charitytuesday @theNSPCC @SparksCharity...

[1600000 rows x 6 columns]

In [6]:
from wordcloud import WordCloud

x=df.iloc[:,-1].to_string()
print(x)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [15]:
x=df.iloc[:,-1].values
y=df.iloc[:,0].values

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import  MultinomialNB

In [19]:
text_model=Pipeline([('tfidf',TfidfVectorizer()),('model',MultinomialNB())])

In [20]:
text_model.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [21]:
y_pred=text_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 4])

In [22]:
y_test

array([0, 0, 0, ..., 0, 4, 4])

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:
accuracy_score(y_pred,y_test)*100

77.340625

In [25]:
confusion_matrix(y_pred,y_test)

array([[197015,  65903],
       [ 42862, 174220]])

In [26]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.82      0.75      0.78    262918
           4       0.73      0.80      0.76    217082

    accuracy                           0.77    480000
   macro avg       0.77      0.78      0.77    480000
weighted avg       0.78      0.77      0.77    480000

