<a href="https://colab.research.google.com/github/shahil2104/Hibernate-ORM-Tutorials/blob/master/major_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as scs

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df=pd.read_csv("/content/drive/My Drive/python.smartknower/training.csv",engine='python',header=None)
df

0  ...                                                  5
0        0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1        0  ...  is upset that he can't update his Facebook by ...
2        0  ...  @Kenichan I dived many times for the ball. Man...
3        0  ...    my whole body feels itchy and like its on fire 
4        0  ...  @nationwideclass no, it's not behaving at all....
...     ..  ...                                                ...
1599995  4  ...  Just woke up. Having no school is the best fee...
1599996  4  ...  TheWDB.com - Very cool to hear old Walt interv...
1599997  4  ...  Are you ready for your MoJo Makeover? Ask me f...
1599998  4  ...  Happy 38th Birthday to my boo of alll time!!! ...
1599999  4  ...  happy #charitytuesday @theNSPCC @SparksCharity...

[1600000 rows x 6 columns]

In [ ]:
from wordcloud import WordCloud

x=df.iloc[:,-1].to_string()
print(x)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
x=df.iloc[:,-1].values
y=df.iloc[:,0].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import  MultinomialNB

In [ ]:
text_model=Pipeline([('tfidf',TfidfVectorizer()),('model',MultinomialNB())])

In [ ]:
text_model.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
y_pred=text_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 4])

In [ ]:
y_test

array([0, 0, 0, ..., 0, 4, 4])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
accuracy_score(y_pred,y_test)*100

77.340625

In [ ]:
confusion_matrix(y_pred,y_test)

array([[197015,  65903],
       [ 42862, 174220]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.82      0.75      0.78    262918
           4       0.73      0.80      0.76    217082

    accuracy                           0.77    480000
   macro avg       0.77      0.78      0.77    480000
weighted avg       0.78      0.77      0.77    480000



In [3]:
!pip install streamlit
!pip install pyngrok

     |████████████████████████████████| 7.2MB 2.9MB/s 
     |████████████████████████████████| 102kB 8.8MB/s 
     |████████████████████████████████| 112kB 37.2MB/s 
     |████████████████████████████████| 4.4MB 41.9MB/s 
     |████████████████████████████████| 122kB 46.1MB/s 
  Created wheel for watchdog: filename=watchdog-0.10.3-cp36-none-any.whl size=73873 sha256=201f9957846246573e67c80e903d6d007c863ba71efef17634ae29e8bde8a329
  Stored in directory: /root/.cache/pip/wheels/a8/1d/38/2c19bb311f67cc7b4d07a2ec5ea36ab1a0a0ea50db994a5bc7
  Created wheel for blinker: filename=blinker-1.4-cp36-none-any.whl size=13450 sha256=5a9187385bbafd427927d1ba13752651fe437f4a738d4e31a7a525a6d5fcb33a
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
  Created wheel for pathtools: filename=pathtools-0.1.2-cp36-none-any.whl size=8785 sha256=1c2832f95c27e0ebdd3296457297a95b7812e571b01fbe7bd516844c973675c6
  Stored in directory: /root/.cache/pip/wheel

  Created wheel for pyngrok: filename=pyngrok-4.1.10-cp36-none-any.whl size=16378 sha256=90ba622cbce2c3a7f53339e19d6038d52c695625760b77047ab1093f1e6871d0
  Stored in directory: /root/.cache/pip/wheels/0d/7f/06/e8079dd6f80eb6683fac47c4e1cb720b61cd82d6e4c13d87a5
Successfully built pyngrok


In [1]:
%%writefile major_project.py
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegession

def user_input():
  Review = st.text_input("enter your review")
  data={"sentiment":Review}
  features= pd.DataFrame{data,index=[0]}
  return features

  st.title("Machine Learning Model")
st.subheader("SENTIMENT ANALYSIS OF REVIEW")
dframe = user_input()
st.write(dframe)

df = pd.read.csv('/content/drive/My Drive/python.smartknower/training.csv')
df ['sentiment']=np.where(df['Score']>3,'Positive','negative')
df =df.drop(['id','time','query','name'])

x =df.iloc[:,0].values
y =df.iloc[:,1].values
test_model =pipeline[('tfidf',TfidfVectorizer(min_df=5,ngrok))]
test_model.fit(x,y)

y_pred = test_model.predict(dframe)

st.write([y_pred])

Writing app-ml.py


In [4]:
from pyngrok import ngrok
ngrok.connect(port='8501')

'http://3cb8f298404b.ngrok.io'

In [ ]:
!streamlit run major_project.py


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:8501
  External URL: http://35.227.43.30:8501

